SP stands for Service Provider
alastria/alastria-identity pull request #102
Opened 2020-05-17 08:59 UTC by nmanero

2020-05-20 09:27 UTC, DrankoLQ approved these changes
🤟

2020-05-22 16:35 UTC, VictorNS69 approved these changes

2020-09-28 12:19 UTC, VictorNS69 commented
@nefera606 es una simple corrección en un Readme, yo creo que se puede añadir sin problmea.

2022-04-01 10:39 UTC, VictorNS69 requested changes
Se corrige a mano

2022-04-01 10:39 UTC, closed without merging